# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'corne nice_nano_v2'
on:
  push:
    branches:
      - master
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
      alphas: '["QWERTY"]'
      clipboard: '["Mac"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y\\nCONFIG_ZMK_SLEEP=y\\nCONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=10\\CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10"]'
      nav: '["vi"]'
